queries:
  list_university_courses:
    query: >
      PREFIX ex: <http://example.org/ns#>
      PREFIX dbo: <http://dbpedia.org/ontology/>
      PREFIX dbr: <http://dbpedia.org/resource/>

      SELECT ?course WHERE {
        dbr:{university} dbo:offersCourse ?course .
      }

  find_courses_by_topic:
    query: >
      PREFIX ex: <http://example.org/vocab/>
      PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

      SELECT ?course ?courseName
      WHERE {
        ?topic ex:topicName "{topic}"^^xsd:string .
        ?topic ex:isTopicOfCourse ?course .
        ?course ex:description ?courseName .
      }

  list_topics_in_course:
    query: >
      PREFIX ex: <http://example.org/vocab/>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

      SELECT ?topicName
      WHERE {
        ?topic ex:isTopicOfCourse <http://example.org/vocab/course/{course_id}> ;
              ex:isTopicOfLecture <http://example.org/vocab/lecture/4> ;
              ex:topicName ?topicName .
      }

  list_courses_by_subject:
    query: >
      PREFIX ex: <http://example.org/vocab/>
      PREFIX dbo: <http://dbpedia.org/ontology/>

      SELECT ?course ?subject ?number
      WHERE {
        ?university dbo:offersCourse ?course .
        ?course a ex:Course ;
                ex:subject ?subject ;
                ex:number ?number .
        FILTER(?subject = "{subject}")
      }

  recommended_materials_for_topic:
    query: >
      PREFIX ex: <http://example.org/ns#>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
      SELECT ?materialType ?lectureContentLink
      WHERE {
        ?course a ex:Course ;
                ex:courseNumber "{courseNumber}"^^xsd:string .
        ?lecture a ex:Lecture ;
                ex:isPartOfCourse ?course .
        ?topic a ex:Topic ;
              ex:topicName "{topic}"^^xsd:string ; 
              ex:isTopicOfLecture ?lecture .
        ?lecture ex:lectureContentLink ?lectureContentLink .
        ?content a ?materialType .
        FILTER(?materialType IN (ex:Slides, ex:Readings))
      }
      
  course_credits:
    query: >
      
  additional_course_resources:
    query: >
      
  detail_course_content:
    query: >
      
  recommended_reading_for_topic:
    query: >
      
  competencies_gained:
    query: >
      
  student_grades:
    query: >
      
  students_completed_course:
    query: >
      
  print_student_transcript:
    query: >
      
  query_course_description:
    query: >
      
  query_topics_in_course_event:
    query: >
      
  query_events_covering_topic:
    query: >
      